name: Deploy Theme to Server

on:
  push:
    branches:
      - main  # Zakładam, że 'main' to główna gałąź. W razie potrzeby zmień na 'master'.

jobs:
  ftp-deploy:
    name: FTP Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy files via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: ${{ secrets.SERVER_DESTINATION }}
          dangerous-clean-slate: true
          # Wykluczamy pliki i foldery, których nie chcemy na serwerze
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            .github/**
